/** Daftar kategori fiqih beserta metadata tampilan */
export const CATEGORIES = [
  {
    key: 'niatDanSyarat',
    label: 'Niat & Syarat',
    emoji: '📋',
    color: 'amber',
    desc: 'Rukun niat dan syarat sah puasa',
  },
  {
    key: 'syaratWajibDanSah',
    label: 'Syarat Wajib & Sah',
    emoji: '📜',
    color: 'amber',
    desc: 'Syarat wajib dan sahnya ibadah puasa',
  },
  {
    key: 'pembatalPuasa',
    label: 'Pembatal Puasa',
    emoji: '⚠️',
    color: 'rose',
    desc: 'Hal-hal yang membatalkan puasa',
  },
  {
    key: 'tidakMembatalkanPuasa',
    label: 'Tidak Membatalkan',
    emoji: '✅',
    color: 'emerald',
    desc: 'Yang dibolehkan saat berpuasa',
  },
  {
    key: 'sunnahDanAdab',
    label: 'Sunnah & Adab',
    emoji: '🌙',
    color: 'indigo',
    desc: 'Amalan sunnah dan adab puasa',
  },
  {
    key: 'makruh',
    label: 'Makruh',
    emoji: '🔸',
    color: 'orange',
    desc: 'Perbuatan yang dimakruhkan',
  },
  {
    key: 'wanita',
    label: 'Fiqih Wanita',
    emoji: '🌸',
    color: 'pink',
    desc: 'Hukum khusus bagi wanita',
  },
  {
    key: 'safarDanKondisiKhusus',
    label: 'Safar & Kondisi Khusus',
    emoji: '✈️',
    color: 'sky',
    desc: 'Hukum saat perjalanan & kondisi darurat',
  },
  {
    key: 'medisKontemporer',
    label: 'Medis Kontemporer',
    emoji: '🏥',
    color: 'teal',
    desc: 'Fatwa medis modern terkait puasa',
  },
  {
    key: 'qadhaFidyahKaffarah',
    label: 'Qadha, Fidyah & Kaffarah',
    emoji: '⚖️',
    color: 'violet',
    desc: 'Penggantian dan denda puasa',
  },
  {
    key: 'khilafiyahMazhab',
    label: 'Khilafiyah Mazhab',
    emoji: '📚',
    color: 'slate',
    desc: 'Perbedaan pendapat antar mazhab',
  },
  {
    key: 'zakatFitrah',
    label: 'Zakat Fitrah',
    emoji: '🌾',
    color: 'lime',
    desc: 'Hukum dan tata cara zakat fitrah',
  },
  {
    key: 'lailatulQadarDanItikaf',
    label: "I'tikaf & Lailatul Qadar",
    emoji: '🕌',
    color: 'cyan',
    desc: "Panduan i'tikaf dan 10 malam terakhir",
  },
  {
    key: 'amalanIdulFitriDanSyawal',
    label: 'Idul Fitri & Syawal',
    emoji: '🎉',
    color: 'yellow',
    desc: 'Amalan hari raya dan puasa Syawal',
  },
  {
    key: 'penentuanHilal',
    label: 'Hilal & Penentuan Ramadhan',
    emoji: '🌙',
    color: 'yellow',
    desc: 'Metode penentuan awal Ramadhan',
  },
  {
    key: 'kasusModern',
    label: 'Kasus Modern',
    emoji: '💡',
    color: 'purple',
    desc: 'Fatwa isu-isu kontemporer',
  },
  {
    key: 'etikaSosialDanDigital',
    label: 'Etika Sosial & Digital',
    emoji: '📱',
    color: 'indigo',
    desc: 'Adab berpuasa di era digital',
  },
  {
    key: 'parentingRamadhan',
    label: 'Parenting Ramadhan',
    emoji: '👨‍👩‍👧',
    color: 'pink',
    desc: 'Mendidik anak berpuasa',
  },
  {
    key: 'tipsKesehatanRamadhan',
    label: 'Tips Kesehatan',
    emoji: '💊',
    color: 'teal',
    desc: 'Menjaga kesehatan saat berpuasa',
  },
  {
    key: 'faktaSejarahRamadhan',
    label: 'Fakta Sejarah',
    emoji: '🏛️',
    color: 'slate',
    desc: 'Peristiwa bersejarah di bulan Ramadhan',
  },
];
